### ISSUE TITLE
Not able to deploy: Err: "PointOfSale" -- [customers] Value must be a MichelsonMap.

### ISSUE THREAD

**Issue by amateur-dev** [claudebarde/tezos-react-tutorial#2]
Trying to deloy but keep getting this error.  
``` "PointOfSale" -- [customers] Value must be a MichelsonMap.```

**Comment by amateur-dev** [comment]
Resolved the error using the following change in the migrations file:

```
......
const { MichelsonMap } = require('@taquito/taquito');
......

const initial_storage = {
  menu: MichelsonMap.fromLiteral({
    "cappuccino": 2500000,
    "latte": 2000000,
    "americano": 1600000,
    "macchiato": 3000000
    }),
  customers: MichelsonMap.fromLiteral({
    [`${alice.pkh}`]: 0
    }),
  total: 0,
  owner: alice.pkh
};
........
```

**Comment by claudebarde** [comment]
I have just cloned and deployed the smart contract on the sandbox node and it works correctly (see the block timestamp in the screenshot).
Could you please give me more details about the steps you took that led to the error you encountered?  
  
<img width="736" alt="Screenshot 2020-04-23 09 54 57" src="https://user-images.githubusercontent.com/25201109/80068699-bcce5600-8548-11ea-94c1-c5285e8b6f6c.png">

**Comment by amateur-dev** [comment]
Strange; I literally did the same thing.  Just cloned and ran your commands; and it gave me the error 
```
"PointOfSale" -- [customers] Value must be a MichelsonMap.
```

**Comment by claudebarde** [comment]
I can see you requested a pull request with a change of Taquito version (^6.1.1-beta.0), I tried it here too and it deploys properly.
Could you make a screenshot of the context where you get this error, please?

**Comment by amateur-dev** [comment]
Damn, surprise surprise; now it deployed.  Damn, this is strange.  I was trying since yesterday and it gave me that error.  Apologies; there must be something else that I may have done wrong.

**Comment by claudebarde** [comment]
Sometimes you do nothing wrong, but the computer has its own will 😁
I will copy-paste below the solution you put in the pull request (in case someone else runs into the same problem) and close it, thank you!

**Comment by claudebarde** [comment]
In case you have the same error, try to replace the following code  
`const initial_storage = {
  menu: {
    cappuccino: 2500000,
    latte: 2000000,
    americano: 1600000,
    macchiato: 3000000
  },
  customers: { [alice.pkh]: 0 }`  
by the following  
`menu: MichelsonMap.fromLiteral({
    "cappuccino": 2500000,
    "latte": 2000000,
    "americano": 1600000,
    "macchiato": 3000000
    }),
  customers: MichelsonMap.fromLiteral({
    [`${alice.pkh}`]: 0
    })`
and add `const { MichelsonMap } = require('@taquito/taquito');` at the top.

**Comment by amateur-dev** [comment]
@claudebarde Found out the issue.  The issue is with the truffle@tezos package.  Updating truffle@tezos to `truffle@5.2.0-tezos.1` gives the error that I mentioned above.  However using `Truffle v5.2.0-tezos.1 (core: 5.2.0-tezos.1)` works just fine.

**Comment by claudebarde** [comment]
I updated my Truffle version and indeed, this raised the issue.
I committed your pull request and tested the code again, it seems that the Taquito version didn't update properly during the merge, so I did it manually.
Thanks a lot for the feedback!
